github:
    client:
        accessTokenUri: https://github.com/login/oauth/access_token
        clientAuthenticationScheme: form
        clientId: 227a46b85870a024516a
        clientSecret: ***
        userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
        userInfoUri: https://api.github.com/user
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
    freemarker:
#        cache: false
#        settings:
#            template_update_delay: 0
        suffix: .ftl
        template-loader-path: classpath:/templates
    jpa:
        database: MYSQL
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: false
